name: web-x
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiofiles=25.1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - annotated-doc=0.0.4
  - annotated-types=0.7.0
  - anyio=4.12.1
  - attrs=25.4.0
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - chameleon=3.9.1
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - daiquiri=3.0.0
  - dnspython=2.8.0
  - email-validator=2.3.0
  - email_validator=2.3.0
  - exceptiongroup=1.3.1
  - fastapi=0.128.0
  - fastapi-cli=0.0.20
  - fastapi-core=0.128.0
  - frozenlist=1.7.0
  - gunicorn=23.0.0
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=78.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - iniconfig=2.3.0
  - jinja2=3.1.6
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libuv=1.51.0
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.2
  - markdown=3.10
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mdurl=0.1.2
  - multidict=6.7.0
  - ncurses=6.5
  - openssl=3.6.0
  - packaging=25.0
  - pip=25.3
  - pluggy=1.6.0
  - propcache=0.3.1
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pydantic-extra-types=2.11.0
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.12.12
  - python-dotenv=1.2.1
  - python-json-logger=2.0.7
  - python-multipart=0.0.21
  - python_abi=3.12
  - pyyaml=6.0.3
  - readline=8.3
  - requests=2.32.5
  - rich=14.2.0
  - rich-toolkit=0.17.1
  - setuptools=80.9.0
  - shellingham=1.5.4
  - sniffio=1.3.1
  - snowballstemmer=3.0.1
  - soupsieve=2.8.1
  - starlette=0.50.0
  - tk=8.6.13
  - tomli=2.3.0
  - typer=0.21.1
  - typer-slim=0.21.1
  - typer-slim-standard=0.21.1
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - uvicorn=0.40.0
  - uvicorn-standard=0.40.0
  - uvloop=0.22.1
  - watchfiles=1.1.1
  - websockets=15.0.1
  - wheel=0.45.1
  - yaml=0.2.5
  - yarl=1.22.0
  - zipp=3.23.0
  - zstd=1.5.7
  - pip:
      - bugle==0.0.4
      - fastapi-chameleon==0.1.12
prefix: /home/servilla/miniconda3/envs/web-x
